### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by uni-j-uni**
issue templates 작

### CODE REVIEW

**Comment by Jindongleee** [comment]
hello

**Review by Jindongleee — CHANGES_REQUESTED** [review]
hello

**Review by uni-j-uni — COMMENTED** [review]
good

**Review by uni-j-uni — COMMENTED** [review]
test

**Review by uni-j-uni — COMMENTED** [review]
test

**Review by Jindongleee — COMMENTED** [review]
good

**Review by Jindongleee — APPROVED** [review]
heejun good

**Review by zmarzmzm — APPROVED** [review]
GOOD

**Comment by Jindongleee** [comment]
dwad

**Review by uni-j-uni — COMMENTED** [review]
D

**Review by Jindongleee — APPROVED** [review]

**Review by uni-j-uni — COMMENTED** [review]
ㅇㅇㄴ

**Pull request closed without merging**
